---
title: " "
format: pdf
editor: visual
geometry: "left=1cm,right=1cm,top=1cm,bottom=1cm"
---

# Lewis HOUNKPEVI

**Location:** Versailles\
**Phone:** +33 6 95 33 59 36\
**Email:** [dumesnil.hounkpevi\@gmail.com](mailto:dumesnil.hounkpevi@gmail.com)\
**LinkedIn:** <https://www.linkedin.com/in/lewishounkpevi>

------------------------------------------------------------------------

## Summary

Experienced Senior Data Scientist with expertise in machine learning, data analysis, and tools such as Python, R, and AWS. Possesses strong leadership and team training experience, with significant contributions across various sectors.

------------------------------------------------------------------------

## Skills

-   **Languages:**
    -   English: Fluent
-   **Data Analysis:**
    -   PCA, MCA, CA, regression, anomaly detection, modeling and scoring, segmentation, classification, risk or propensity assessment
-   **Machine Learning And MLOps:**
    -   Xgboost, GBM, Random Forest, KMeans, CAH, Dbscan, Deep Learning
    -   MLflow, FastApi, Flask, CI/CD
-   **Technical Environment:**
    -   Expert in R, Python, SQL, Git, AWS SageMaker, S3, Redshift, Docker, PowerBI

------------------------------------------------------------------------

## Professional Experience

**Senior Data Scientist – Santevet – Full remote**\
*July 2022 – Present*\
- Centralized churn-related analyses.

\- Assisted various departments (Actuarial, Finance, Marketing, and Commerce) in reducing churn.

\- Portfolio segmentation, churn scoring using Python and AWS SageMaker, S3.

-   Technical lead of a team of 3 collaborators.

**Key Achievements:**

\- Reduced churn by 10% using scoring models with Python.

\- Improved team efficiency by 20% by automating analysis processes.

------------------------------------------------------------------------

**Senior Data Scientist at the Directorate of Studies and Analyses – Unédic – Paris**\
*September 2019 – June 2022*\
- Provided technical support and skill development for the Unédic team on new data analysis tools.

\- Conducted training and technical support on R, Python, Spark (Sparklyr and Pyspark), and Git.

\- Published several articles on job seeker typology and was part of the team dedicated to work on Partial Activity during the COVID crisis.

**Key Achievements:**

\- Published 5 technical articles on job seeker analysis.

\- Trained over 50 employees on modern data science tools.

------------------------------------------------------------------------

**Lead Data Scientist at the Marketing Department – Eni Gas & Power – Levallois**\
*February 2018 – August 2019*\
- Responsible for statistical analysis, modeling, and KPI monitoring for B2C and B2B segments at Eni.

\- Developed churn, cross-sell, and service propensity scores for offerings, contributing to a 10% churn reduction and a 15% increase in cross-sell.

\- Identified different customer profiles through segmentation.

\- Created R packages to improve productivity and reproducibility of analyses and studies.

\- Technical lead of a team of 3 people.

**Key Achievements:**

\- Reduced churn by 10% and increased cross-sell by 15%.

\- Developed 3 R packages that increased productivity by 25%.

------------------------------------------------------------------------

**Technical Lead Data Scientist - Consulting for Renault (Altran, Ligeron) – Paris**\
*May 2014 – January 2018*\
- 4 years of experience in data science, with expertise in ML, using R, Python, SQL, Git.

\- Expertise in data analysis, customer segmentation, and scoring.

\- Skills in automating analysis reports and data visualization with a focus on clarity, pedagogy, and precision in data analysis.

**Key Achievements:**

\- Implemented ML solutions that reduced analysis costs by 30%.

\- Automated reports, reducing generation time by 40%.

------------------------------------------------------------------------

## Education

-   **Specialization in Building Cloud Computing Solutions at Scale** - Coursera - 2024
-   **Master’s Degree in Statistical Engineering** - University of Cergy-Pontoise, France - 2014

------------------------------------------------------------------------

## Personal Projects and Open Source Contributions

-   **Kaggle Competitions:** Participated in several competitions with notable results.
-   **GitHub Contributions:** Developed and shared multiple packages and scripts useful to the data science community.

------------------------------------------------------------------------

## Publications and Conferences

-   **Publications:** 5 technical articles on job seeker analysis.
-   **Conferences:** Presentations at conferences such as Data Science Paris and PyCon.
