name: Render CV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.0'

    - name: Install Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.0/quarto-1.2.0-linux-amd64.deb
        sudo dpkg -i quarto-1.2.0-linux-amd64.deb

    - name: Install R dependencies
      run: |
        R -e "install.packages('quarto')"
        R -e "install.packages('rmarkdown')"

    - name: Render CV
      run: |
        quarto render fr_cv_updated_LHO.qmd --to PrettyPDF-pdf --no-watch-inputs --no-browse

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: cv-pdf
        path: cv.pdf

    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.CV_TOKEN }}
        publish_dir: ./_site
